module.exports = {
  env: {
    'jest/globals': true,
    browser: true,
  },
  extends: [
    'eslint-config-airbnb',
    'eslint-config-prettier',
    'eslint-config-prettier/react',
  ].map(require.resolve),
  parser: 'babel-eslint',
  plugins: ['jest', 'prettier'],
  rules: {
    'arrow-body-style': 0,
    'arrow-parens': ['error', 'as-needed'],
    camelcase: ['error'],
    'no-prototype-builtins': 0,
    'import/prefer-default-export': 0,
    'import/no-named-default': 0,
    'import/first': 0,
    'import/no-unresolved': 0,
    'import/no-extraneous-dependencies': 0,
    'no-underscore-dangle': [2, { allowAfterThis: true }],
    semi: [2, 'never'],
    'no-plusplus': ['warn'],
    'react/jsx-no-bind': 0,
    'react/prefer-stateless-function': 0,
    'react/sort-comp': 0,
    'react/jsx-filename-extension': 0,
    'jest/no-disabled-tests': 'warn',
    'jest/no-focused-tests': 'error',
    'jest/no-identical-title': 'error',
    'jest/valid-expect': 'error',
    'prettier/prettier': [
      'error',
      {
        printWidth: 80,
        singleQuote: true,
        semi: false,
        trailingComma: 'es5',
      },
    ],
    'no-multiple-empty-lines': [
      'error',
      {
        max: 1,
        maxEOF: 0,
      },
    ],
  },
}
